
-- Create profiles table
create table public.profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  xp integer default 0,
  level integer default 1,
  updated_at timestamp with time zone,

  constraint username_length check (char_length(username) >= 3)
);

-- Internal policies for profiles
alter table public.profiles enable row level security;

create policy "Public profiles are viewable by everyone."
  on profiles for select
  using ( true );

create policy "Users can insert their own profile."
  on profiles for insert
  with check ( auth.uid() = id );

create policy "Users can update own profile."
  on profiles for update
  using ( auth.uid() = id );

-- Create predictions table
create table public.predictions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  match_id integer not null,
  home_team text not null,
  away_team text not null,
  predicted_winner text not null,
  confidence integer not null,
  ai_analysis text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Internal policies for predictions
alter table public.predictions enable row level security;

create policy "Predictions are viewable by everyone."
  on predictions for select
  using ( true );

create policy "Users can insert their own predictions."
  on predictions for insert
  with check ( auth.uid() = user_id );
